name: Run analysis_main.py on push

on:
  push:
    branches: [ main ]         # 触发条件：main 分支 push
  workflow_dispatch:           # 支持手动触发

jobs:
  run-analysis:
    runs-on: ubuntu-latest      # 使用 GitHub 最新官方 Linux 服务器

    steps:
      - uses: actions/checkout@v3    # 检出代码

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"      # Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # 安装你项目根目录下的 requirements.txt

      - name: Run analysis_main.py
        run: python analysis_main.py        # 执行你的主脚本
