name: Run analysis_main.py on push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-analysis-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果有 requirements.txt 取消下面注释
        # pip install -r requirements.txt

    - name: Run analysis_main.py
      run: python analysis_main.py
