name: News Crawler

on:
  schedule:
    - cron: "0,30 * * * *"  # 每半小时运行一次（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Microsoft Edge Browser and WebDriver
        run: |
          # 安装 Microsoft Edge 浏览器
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-edge.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
          sudo apt update
          sudo apt install -y microsoft-edge-stable

          # 获取已安装的 Edge 版本
          EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}')
          echo "Installed Edge version: $EDGE_VERSION"

          # 下载匹配的 WebDriver
          wget "https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip" -O edgedriver.zip
          unzip edgedriver.zip -d /usr/local/bin
          chmod +x /usr/local/bin/msedgedriver
          rm edgedriver.zip

          # 验证安装
          echo "WebDriver version:"
          msedgedriver --version

      - name: Run crawler
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python news_crawler.py
